site_name: Smart Recruiter
site_url: https://bintybyte.com/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Home: index.md
  - Introduction: introduction.md
  - System Requirements: system_requirements.md
  - Configure Dependencies: configure_dependencies.md
  - Installation & Deployment: installation_deployment.md
  - Configuring Input & Output Folders: configuring_io_folders.md
  - Run the Application: run_application.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - with-pdf:
      author: BintyByte
      copyright: "Copyright &copy; 2024 BintyByte"
      cover: true
      cover_title: "Smart Recruiter Documentation"
      cover_subtitle: "Version 1.0"
      toc_title: "Table of Contents"
      toc_level: 3
      ordered_chapter_level: 3
      output_path: pdf/UserGuide.pdf
      custom_template_path: templates  # Optional if you have custom templates

copyright: Copyright &copy; 2024 BintyByte